"""initial revision

Revision ID: bad3f9a6c4fb
Revises: 
Create Date: 2025-03-26 03:34:16.795975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad3f9a6c4fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('bandwidth', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_requests_address'), 'wallet_requests', ['address'], unique=False)
    op.create_index(op.f('ix_wallet_requests_id'), 'wallet_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_requests_id'), table_name='wallet_requests')
    op.drop_index(op.f('ix_wallet_requests_address'), table_name='wallet_requests')
    op.drop_table('wallet_requests')
    # ### end Alembic commands ###
